TOKEN=""
guild_id=1234567890 #placeholder
bot_logo="https://discord.com/assets/259560fbae59ef36798b.png" #placeholder



[leveling]
xp=25 # how much xp to give per message sent.
ignore_channels=[] #channel IDs
